# Generated by Django 3.0.8 on 2022-03-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_area', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=255, unique=True)),
                ('_password', models.CharField(max_length=255)),
                ('_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_api.Area')),
            ],
        ),
    ]
